apiVersion: v1
kind: PersistentVolume
metadata:
  name: new-shared-pv
spec:
  capacity:
    storage: 1Gi  # Adjust this value as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/data/shared"
    type: DirectoryOrCreate
