apiVersion: v1
kind: ServiceAccount
metadata:
  name: project-manager-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: project-manager-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project-manager-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: project-manager-sa
  namespace: default
roleRef:
  kind: Role
  name: project-manager-role
  apiGroup: rbac.authorization.k8s.io
